import { Language } from '../types';

export interface HPWordItem {
  fr: string;
  en: string;
}

export const HP_CONCEPTS: HPWordItem[] = [
  {"fr": "ALCHIMIE", "en": "ALCHEMY"},
  {"fr": "ALLIANCE", "en": "ALLIANCE"},
  {"fr": "AMORTENTIA", "en": "AMORTENTIA"},
  {"fr": "AMULETTE", "en": "AMULET"},
  {"fr": "ANIMAGUS", "en": "ANIMAGUS"},
  {"fr": "ANNIVERSAIRE", "en": "DEATHDAY"},
  {"fr": "APPARITION", "en": "APPARITION"},
  {"fr": "ARBALÈTE", "en": "CROSSBOW"},
  {"fr": "ARITHMANCIE", "en": "ARITHMANCY"},
  {"fr": "ARMÉE DE DUMBLEDORE", "en": "DUMBLEDORE'S ARMY"},
  {"fr": "ARSENAL", "en": "ARSENAL"},
  {"fr": "ASPIC", "en": "NEWT"},
  {"fr": "ATTAPEUR", "en": "SEEKER"},
  {"fr": "AUBERGE", "en": "INN"},
  {"fr": "AUGUREY", "en": "AUGUREY"},
  {"fr": "AUROR", "en": "AUROR"},
  {"fr": "AUTEL", "en": "ALTAR"},
  {"fr": "AVALANCHE", "en": "AVALANCHE"},
  {"fr": "BADGE", "en": "BADGE"},
  {"fr": "BAGARRE", "en": "BRAWL"},
  {"fr": "BAIN", "en": "BATH"},
  {"fr": "BALEINE", "en": "WHALE"},
  {"fr": "BANDEROLLE", "en": "BANNER"},
  {"fr": "BANQUET", "en": "FEAST"},
  {"fr": "BARBE", "en": "BEARD"},
  {"fr": "BARGHEST", "en": "BARGHEST"},
  {"fr": "BARIL", "en": "BARREL"},
  {"fr": "BARRIÈRE", "en": "BARRIER"},
  {"fr": "BATTE", "en": "BAT"},
  {"fr": "BATTEUR", "en": "BEATER"},
  {"fr": "BAVOLETTES", "en": "GOBSTONES"},
  {"fr": "BEAUXTÂTONS", "en": "BEAUXBATONS"},
  {"fr": "BÉBÉ", "en": "BABY"},
  {"fr": "BÉTA", "en": "BETA"},
  {"fr": "BIBLIOTHÈQUE", "en": "LIBRARY"},
  {"fr": "BIJOU", "en": "JEWEL"},
  {"fr": "BOCAL", "en": "JAR"},
  {"fr": "BOIS", "en": "WOOD"},
  {"fr": "BOLET", "en": "BOLETE"},
  {"fr": "BOMBE", "en": "BOMB"},
  {"fr": "BONNET", "en": "BONNET"},
  {"fr": "BORGAT", "en": "BOGGART"},
  {"fr": "BOUCLIER", "en": "SHIELD"},
  {"fr": "BOUÈLE", "en": "GUT"},
  {"fr": "BOUGIE FLOTTANTE", "en": "FLOATING CANDLE"},
  {"fr": "BOULE DE PUDING", "en": "PUDDING"},
  {"fr": "BOUTEILLE DE BIÈRE", "en": "BOTTLE"},
  {"fr": "BOUTON", "en": "BUTTON"},
  {"fr": "BOWTRUCKLE", "en": "BOWTRUCKLE"},
  {"fr": "BRASERO", "en": "BRAZIER"},
  {"fr": "BRÈCHE", "en": "BREACH"},
  {"fr": "BRIGADE", "en": "SQUAD"},
  {"fr": "BRIQUET", "en": "DELUMINATOR"},
  {"fr": "BRONZE", "en": "BRONZE KNUT"},
  {"fr": "BROUILLARD", "en": "MIST"},
  {"fr": "BRÛLURE", "en": "BURN"},
  {"fr": "BUSE", "en": "OWL EXAM"},
  {"fr": "CABINET", "en": "OFFICE"},
  {"fr": "CACHOT", "en": "CELL"},
  {"fr": "CADAVRE", "en": "CORPSE"},
  {"fr": "CADRAN", "en": "DIAL"},
  {"fr": "CAGE", "en": "CAGE"},
  {"fr": "CALÈCHE", "en": "CARRIAGE"},
  {"fr": "CAMÉLÉON", "en": "CHAMELEON"},
  {"fr": "CANARD", "en": "RUBBER DUCK"},
  {"fr": "CANON", "en": "CANNON"},
  {"fr": "CANOPÉE", "en": "CANOPY"},
  {"fr": "CAPITALE", "en": "CAPITAL"},
  {"fr": "CAPITAINE", "en": "CAPTAIN"},
  {"fr": "CARAPACE", "en": "SHELL"},
  {"fr": "CARNAVAL", "en": "CARNIVAL"},
  {"fr": "CARROSSE", "en": "COACH"},
  {"fr": "CASCADE", "en": "WATERFALL"},
  {"fr": "CASQUE", "en": "HELMET"},
  {"fr": "CATALYSEUR", "en": "CATALYST"},
  {"fr": "CAVERNE", "en": "CAVE"},
  {"fr": "CELLULE", "en": "CELL"},
  {"fr": "CENDRES CHAUDES", "en": "EMBER"},
  {"fr": "CERCLE DE PIERRES", "en": "STONE CIRCLE"},
  {"fr": "CÉRÉMONIE", "en": "CEREMONY"},
  {"fr": "CERF", "en": "STAG"},
  {"fr": "CHAÎNE BRISÉE", "en": "BROKEN CHAIN"},
  {"fr": "CHALET", "en": "COTTAGE"},
  {"fr": "CHAMBRE", "en": "CHAMBER"},
  {"fr": "CHAMPIGNON LUMINEUX", "en": "GLOWING MUSHROOM"},
  {"fr": "CHAPEAU POINTU", "en": "POINTED HAT"},
  {"fr": "CHARIOT", "en": "TROLLEY"},
  {"fr": "CHASSEUR", "en": "HUNTER"},
  {"fr": "CHAT DU CHEMIN", "en": "KNEAZLE"},
  {"fr": "CHÂTIMENT", "en": "PUNISHMENT"},
  {"fr": "CHEMIN DE FER", "en": "RAILWAY"},
  {"fr": "CHEVAL SAUVAGE", "en": "WINGED HORSE"},
  {"fr": "CHIMÈRE", "en": "CHIMERA"},
  {"fr": "CHOU MORDANT", "en": "BITING CABBAGE"},
  {"fr": "CHRONOMÈTRE", "en": "STOPWATCH"},
  {"fr": "CHUCHOTEMENT", "en": "WHISPER"},
  {"fr": "CHUTE LIBRE", "en": "FREE FALL"},
  {"fr": "CIMIER", "en": "CREST"},
  {"fr": "CIRQUE", "en": "CIRCUS"},
  {"fr": "CLAN", "en": "CLAN"},
  {"fr": "CLOCHE DE VERRE", "en": "BELL JAR"},
  {"fr": "COBRA", "en": "COBRA"},
  {"fr": "COCKTAIL", "en": "BREWAGE"},
  {"fr": "COLLAPSIBLE", "en": "COLLAPSIBLE"},
  {"fr": "COLLECTION", "en": "COLLECTION"},
  {"fr": "COLLIER D'OPALES", "en": "OPAL NECKLACE"},
  {"fr": "COMBAT", "en": "DUEL"},
  {"fr": "COMMERCE", "en": "SHOP"},
  {"fr": "COMPAS", "en": "COMPASS"},
  {"fr": "COMPLOT", "en": "PLOT"},
  {"fr": "CONCOURS", "en": "CONTEST"},
  {"fr": "CONFISERIE", "en": "CONFECTIONERY"},
  {"fr": "CONFLIT", "en": "STRIFE"},
  {"fr": "CONFRÉRIE", "en": "BROTHERHOOD"},
  {"fr": "CONGRÈS", "en": "CONGRESS"},
  {"fr": "CORBEAU", "en": "RAVEN"},
  {"fr": "CORNE D'ÉLUMPENT", "en": "ERUMPENT HORN"},
  {"fr": "CORRIDOR", "en": "CORRIDOR"},
  {"fr": "COUTEAU D'ARGENT", "en": "SILVER KNIFE"},
  {"fr": "COUVENT", "en": "CONVENT"},
  {"fr": "CRÂNE D'OISEAU", "en": "BIRD SKULL"},
  {"fr": "CRAPAUD CORNU", "en": "HORNED TOAD"},
  {"fr": "CRÊTE", "en": "RIDGE"},
  {"fr": "CRI DU FANTÔME", "en": "WAIL"},
  {"fr": "CROC", "en": "TUSK"},
  {"fr": "CROCODILE", "en": "CROCODILE"},
  {"fr": "CROIX", "en": "CROSS"},
  {"fr": "CRYPTE", "en": "CRYPT"},
  {"fr": "CUIR", "en": "LEATHER"},
  {"fr": "CUISINE DES ELFES", "en": "KITCHEN"},
  {"fr": "CYGNE", "en": "SWAN"},
  {"fr": "DAGUE", "en": "DAGGER"},
  {"fr": "DALLE", "en": "SLAB"},
  {"fr": "DANGEREUX", "en": "HAZARDOUS"},
  {"fr": "DARD DE VRILLE", "en": "STINGER"},
  {"fr": "DÉBORDEMENT", "en": "SURGE"},
  {"fr": "DÉCRET", "en": "EDUCATIONAL DECREE"},
  {"fr": "DÉFENSE", "en": "DEFENSE"},
  {"fr": "DÉGUISEMENT", "en": "DISGUISE"},
  {"fr": "DELPHINIUM", "en": "DELPHINIUM"},
  {"fr": "DÉLUGE", "en": "DELUGE"},
  {"fr": "DÉMON", "en": "DEMON"},
  {"fr": "DÉPÊCHE", "en": "DISPATCH"},
  {"fr": "DÉSINTÉGRATION", "en": "SPLINCHING"},
  {"fr": "DESTIN", "en": "DESTINY"},
  {"fr": "DEUIL", "en": "MOURNING"},
  {"fr": "DIABLE DE POCHE", "en": "IMP"},
  {"fr": "DICTAPHONE", "en": "QUICK-QUOTES QUILL"},
  {"fr": "DÎNER", "en": "DINNER"},
  {"fr": "DISCIPLINE", "en": "DISCIPLINE"},
  {"fr": "DISCUSSION", "en": "PARLEY"},
  {"fr": "DISTILLERIE", "en": "DISTILLERY"},
  {"fr": "DIVINATION", "en": "DIVINATION"},
  {"fr": "DOCUMENTS", "en": "RECORDS"},
  {"fr": "DOMICILE", "en": "DWELLING"},
  {"fr": "DORTOIR", "en": "DORMITORY"},
  {"fr": "DOUBLE FOND", "en": "FALSE BOTTOM"},
  {"fr": "DRAINEUR", "en": "DRAINER"},
  {"fr": "DRAP", "en": "SHROUD"},
  {"fr": "DRUMSTRANG", "en": "DURMSTRANG"},
  {"fr": "ÉBÈNE", "en": "EBONY"},
  {"fr": "ÉCAILLES DE DRAGON", "en": "DRAGON SCALES"},
  {"fr": "ÉCHANGE", "en": "TRADE"},
  {"fr": "ÉCHIQUIER", "en": "CHESSBOARD"},
  {"fr": "ÉCHO", "en": "ECHO"},
  {"fr": "ÉCLIPSE", "en": "ECLIPSE"},
  {"fr": "ÉCOLE DE MAGIE", "en": "WIZARDING SCHOOL"},
  {"fr": "ÉCORCE", "en": "BARK"},
  {"fr": "ÉCRAN DE FUMÉE", "en": "SMOKESCREEN"},
  {"fr": "ÉCRITURE ANCIENNE", "en": "RUNES"},
  {"fr": "ÉLIXIR", "en": "ELIXIR"},
  {"fr": "EMBARRAS", "en": "PLIGHT"},
  {"fr": "ÉMERAUDE", "en": "EMERALD"},
  {"fr": "EMPIRE", "en": "IMPERIUS"},
  {"fr": "EMPREINTE DE PATTE", "en": "PAWPRINT"},
  {"fr": "ENGRENAGE", "en": "GEAR"},
  {"fr": "ÉNIGME", "en": "RIDDLE"},
  {"fr": "ENSORCELLEMENT", "en": "BEWITCHMENT"},
  {"fr": "ENTRACTE", "en": "INTERVAL"},
  {"fr": "ENVELOPPE", "en": "ENVELOPE"},
  {"fr": "ÉPOUVANTAIL", "en": "SCARECROW"},
  {"fr": "ÉPREUVE", "en": "TRIAL"},
  {"fr": "ÉRUPTIF", "en": "VOLATILE"},
  {"fr": "ESCARGOT", "en": "SNAIL"},
  {"fr": "ESPÈCE", "en": "SPECIES"},
  {"fr": "ÉTANG", "en": "POND"},
  {"fr": "ÉTINCELLE", "en": "SPARK"},
  {"fr": "ÉTOFFE", "en": "FABRIC"},
  {"fr": "ÉTRANGLEUR", "en": "GRINDYLOW"},
  {"fr": "ÉVASION", "en": "BREAKOUT"},
  {"fr": "EXAMEN", "en": "EXAM"},
  {"fr": "EXPÉDITION", "en": "EXPEDITION"},
  {"fr": "EXPLOSION", "en": "BLAST"},
  {"fr": "EXTRAIT", "en": "EXTRACT"},
  {"fr": "FAISCEAU", "en": "BEAM"},
  {"fr": "FALAISE", "en": "CLIFF"},
  {"fr": "FAMILIER", "en": "FAMILIAR"},
  {"fr": "FANATIQUE", "en": "ZEALOT"},
  {"fr": "FARCEUR", "en": "TRICKSTER"},
  {"fr": "FARDEAU", "en": "BURDEN"},
  {"fr": "FAUCON", "en": "FALCON"},
  {"fr": "FAUX", "en": "SCYTHE"},
  {"fr": "FENDU", "en": "CLEFT"},
  {"fr": "FER DE CHEVAL", "en": "HORSESHOE"},
  {"fr": "FERMETURE", "en": "LOCK"},
  {"fr": "FESTIN", "en": "BANQUET"},
  {"fr": "FEU DE CAMP", "en": "CAMPFIRE"},
  {"fr": "FEU FOLLET", "en": "WILL-O'-WISP"},
  {"fr": "FEU VERT", "en": "GREEN LIGHT"},
  {"fr": "FIOLE", "en": "PHIAL"},
  {"fr": "FLACON", "en": "FLASK"},
  {"fr": "FLANELLE", "en": "FLANNEL"},
  {"fr": "FLÈCHE NOIRE", "en": "BLACK ARROW"},
  {"fr": "FLEUR DE LYS", "en": "LILY"},
  {"fr": "FLOTTE", "en": "FLEET"},
  {"fr": "FONDATION", "en": "FOUNDING"},
  {"fr": "FONTAINE DE LA FORTUNE", "en": "FOUNTAIN"},
  {"fr": "FOSSE", "en": "PIT"},
  {"fr": "FOUDRE DE GUERRE", "en": "THUNDER"},
  {"fr": "FOUET", "en": "WHIP"},
  {"fr": "FOURRURE", "en": "FUR"},
  {"fr": "FUGITIF", "en": "FUGITIVE"},
  {"fr": "FUSÉE DE FEU D'ARTIFICE", "en": "FIREWORK"},
  {"fr": "GAGE", "en": "TOKEN"},
  {"fr": "GARDE DU CORPS", "en": "BODYGUARD"},
  {"fr": "GARDIEN", "en": "KEEPER"},
  {"fr": "GARGOYLLE", "en": "GARGOYLE"},
  {"fr": "GEÔLE", "en": "JAIL"},
  {"fr": "GÉO-LOCALISATION", "en": "TRACER"},
  {"fr": "GLACE NOIRE", "en": "BLACK ICE"},
  {"fr": "GLOIRE", "en": "GLORY"},
  {"fr": "GNOME", "en": "GNOME"},
  {"fr": "GOURDIN", "en": "CLUB"},
  {"fr": "GRAAL", "en": "GRAIL"},
  {"fr": "GRAND-DUC", "en": "GREAT OWL"},
  {"fr": "GRATTE-CIEL", "en": "SKYSCRAPER"},
  {"fr": "GRENAT", "en": "GARNET"},
  {"fr": "GRIFFE", "en": "CLAW"},
  {"fr": "GRIFFON", "en": "GRIFFIN"},
  {"fr": "GROTTE DE GLACE", "en": "SEA CAVE"},
  {"fr": "GUIDE", "en": "GUIDE"},
  {"fr": "GUILLOTINE", "en": "GUILLOTINE"},
  {"fr": "HABIT", "en": "ROBES"},
  {"fr": "HAMAC", "en": "HAMMOCK"},
  {"fr": "HARPIE", "en": "HARPY"},
  {"fr": "HAUTEUR", "en": "HEIGHT"},
  {"fr": "HÉLICE", "en": "PROPELLER"},
  {"fr": "HÉRITAGE", "en": "HEIR"},
  {"fr": "HERBE DU SOMMEIL", "en": "SLEEPING HERB"},
  {"fr": "HERBORISTERIE", "en": "HERBOLOGY"},
  {"fr": "HIPPOGRIFFE", "en": "HIPPOGRIFF"},
  {"fr": "HOCHET", "en": "RATTLE"},
  {"fr": "HOMONCULE", "en": "HOMUNCULUS"},
  {"fr": "HÔTE", "en": "HOST"},
  {"fr": "HÔTEL DES MONNAIES", "en": "MINT"},
  {"fr": "HOUX", "en": "HOLLY"},
  {"fr": "HUILE DE SERPENT", "en": "SNAKE OIL"},
  {"fr": "ILLUSION", "en": "ILLUSION"},
  {"fr": "IMPASSE", "en": "DEAD END"},
  {"fr": "INCANTATION", "en": "INCANTATION"},
  {"fr": "INDICE", "en": "CLUE"},
  {"fr": "INFECTION", "en": "INFECTION"},
  {"fr": "INQUISITEUR", "en": "INQUISITOR"},
  {"fr": "INSIGNE", "en": "INSIGNIA"},
  {"fr": "INSTRUMENT", "en": "INSTRUMENT"},
  {"fr": "INTRUS", "en": "INTRUDER"},
  {"fr": "INVOCATION", "en": "SUMMONING"},
  {"fr": "ISOLATION", "en": "ISOLATION"},
  {"fr": "JABOT", "en": "RUFFLE"},
  {"fr": "JARDINIER", "en": "GROUNDSKEEPER"},
  {"fr": "JASPE", "en": "JASPER"},
  {"fr": "JAVELOT", "en": "JAVELIN"},
  {"fr": "JETON", "en": "CHIP"},
  {"fr": "JONCTION", "en": "JUNCTION"},
  {"fr": "JOUET", "en": "TOY"},
  {"fr": "JURON", "en": "CURSE"},
  {"fr": "JUSTICE", "en": "JUSTICE"},
  {"fr": "LAME DE RASOIR", "en": "RAZOR"},
  {"fr": "LANCEMENT", "en": "LAUNCH"},
  {"fr": "LANTERNE", "en": "LANTERN"},
  {"fr": "LÉGILIMENCIE", "en": "LEGILIMENCY"},
  {"fr": "LÉVIATHAN", "en": "SEA MONSTER"},
  {"fr": "LÉVITATION", "en": "LEVITATION"},
  {"fr": "LIÈGE", "en": "CORK"},
  {"fr": "LIGUE", "en": "LEAGUE"},
  {"fr": "LIMACE", "en": "SLUG"},
  {"fr": "LINGOT", "en": "INGOT"},
  {"fr": "LITIÈRE", "en": "LITTER"},
  {"fr": "LOGE", "en": "LODGE"},
  {"fr": "LONGE", "en": "REIN"},
  {"fr": "LOUPE", "en": "MAGNIFIER"},
  {"fr": "LUTIN DE CORNOUAILLES", "en": "PIXIE"},
  {"fr": "MAGICIEN", "en": "WIZARD"},
  {"fr": "MAILLE", "en": "MAIL"},
  {"fr": "MALÉDICTION", "en": "HEX"},
  {"fr": "MALLE", "en": "TRUNK"},
  {"fr": "MANOIR", "en": "MANOR"},
  {"fr": "MARCHAND", "en": "MERCHANT"},
  {"fr": "MARIN", "en": "SAILOR"},
  {"fr": "MARQUE NOIRE", "en": "DARK MARK"},
  {"fr": "MASQUE DE MANGEMORT", "en": "DEATH EATER MASK"},
  {"fr": "MASSUE", "en": "BLUDGEON"},
  {"fr": "MÉDAILLE", "en": "MEDAL"},
  {"fr": "MÉDECINE", "en": "HEALING"},
  {"fr": "MÉNAGERIE", "en": "MENAGERIE"},
  {"fr": "MENSONGE", "en": "LIE"},
  {"fr": "MERCURE", "en": "QUICKSILVER"},
  {"fr": "MESSAGER", "en": "MESSENGER"},
  {"fr": "MÉTALLURGIE", "en": "METALLURGY"},
  {"fr": "MIAULEMENT", "en": "MEOW"},
  {"fr": "MINEUR", "en": "MINER"},
  {"fr": "MIRACLE", "en": "MIRACLE"},
  {"fr": "MIROIR DU RISÉD", "en": "ERIDED MIRROR"},
  {"fr": "MISÉRICORDE", "en": "MERCY"},
  {"fr": "MONSTRE DU LIVRE", "en": "MONSTER BOOK"},
  {"fr": "MONTURE", "en": "MOUNT"},
  {"fr": "MOQUERIE", "en": "MOCKERY"},
  {"fr": "MORCEAU", "en": "SHARD"},
  {"fr": "MORSURE DE LOUP", "en": "WOLF BITE"},
  {"fr": "MORTIER", "en": "MORTAR"},
  {"fr": "MOT D'ORDRE", "en": "WATCHWORD"},
  {"fr": "MOULIN", "en": "MILL"},
  {"fr": "MUGISSEMENT", "en": "ROAR"},
  {"fr": "MUTATION", "en": "MUTATION"},
  {"fr": "MYSTIFICATEUR", "en": "HOAXER"}
];

export const HP_CHARACTERS: HPWordItem[] = [
  {"fr": "HARRY", "en": "HARRY"},
  {"fr": "RON", "en": "RON"},
  {"fr": "HERMIONE", "en": "HERMIONE"},
  {"fr": "DUMBLEDORE", "en": "DUMBLEDORE"},
  {"fr": "VOLDEMORT", "en": "VOLDEMORT"},
  {"fr": "ROGUE", "en": "SNAPE"},
  {"fr": "SIRIUS", "en": "SIRIUS"},
  {"fr": "LUPIN", "en": "LUPIN"},
  {"fr": "HAGRID", "en": "HAGRID"},
  {"fr": "MALEFOY", "en": "MALFOY"},
  {"fr": "DRACO", "en": "DRACO"},
  {"fr": "LUCIUS", "en": "LUCIUS"},
  {"fr": "NARCISSA", "en": "NARCISSA"},
  {"fr": "BELLATRIX", "en": "BELLATRIX"},
  {"fr": "NEVILLE", "en": "NEVILLE"},
  {"fr": "LUNA", "en": "LUNA"},
  {"fr": "GINNY", "en": "GINNY"},
  {"fr": "FRED", "en": "FRED"},
  {"fr": "GEORGE", "en": "GEORGE"},
  {"fr": "PERCY", "en": "PERCY"},
  {"fr": "BILL", "en": "BILL"},
  {"fr": "CHARLIE", "en": "CHARLIE"},
  {"fr": "ARTHUR", "en": "ARTHUR"},
  {"fr": "MOLLY", "en": "MOLLY"},
  {"fr": "MCGONAGALL", "en": "MCGONAGALL"},
  {"fr": "FLITWICK", "en": "FLITWICK"},
  {"fr": "CHOUETTE", "en": "SPROUT"},
  {"fr": "TRELAWNEY", "en": "TRELAWNEY"},
  {"fr": "SLUGHORN", "en": "SLUGHORN"},
  {"fr": "LOCKHART", "en": "LOCKHART"},
  {"fr": "QUIRRELL", "en": "QUIRRELL"},
  {"fr": "FOL OEIL", "en": "MAD-EYE"},
  {"fr": "MOODY", "en": "MOODY"},
  {"fr": "TONKS", "en": "TONKS"},
  {"fr": "KINGSLEY", "en": "KINGSLEY"},
  {"fr": "FUDGE", "en": "FUDGE"},
  {"fr": "OMBRAGE", "en": "UMBRIDGE"},
  {"fr": "SCRIMGEOUR", "en": "SCRIMGEOUR"},
  {"fr": "CROUPIA", "en": "CROUCH"},
  {"fr": "BAGMAN", "en": "BAGMAN"},
  {"fr": "PETTIGROW", "en": "PETTIGREW"},
  {"fr": "QUEUETENDRE", "en": "WORMTAIL"},
  {"fr": "GRINDELWALD", "en": "GRINDELWALD"},
  {"fr": "KARKAROFF", "en": "KARKAROFF"},
  {"fr": "MAXIME", "en": "MAXIME"},
  {"fr": "FLEUR", "en": "FLEUR"},
  {"fr": "KRUM", "en": "KRUM"},
  {"fr": "CEDRIC", "en": "CEDRIC"},
  {"fr": "DIGGORY", "en": "DIGGORY"},
  {"fr": "CHO", "en": "CHO"},
  {"fr": "PANSY", "en": "PANSY"},
  {"fr": "CRABBE", "en": "CRABBE"},
  {"fr": "GOYLE", "en": "GOYLE"},
  {"fr": "ZABINI", "en": "ZABINI"},
  {"fr": "NOTT", "en": "NOTT"},
  {"fr": "SEAMUS", "en": "SEAMUS"},
  {"fr": "DEAN", "en": "DEAN"},
  {"fr": "PARVATI", "en": "PARVATI"},
  {"fr": "PADMA", "en": "PADMA"},
  {"fr": "LAVANDE", "en": "LAVENDER"},
  {"fr": "COLIN", "en": "COLIN"},
  {"fr": "DENNIS", "en": "DENNIS"},
  {"fr": "OLIVER", "en": "OLIVER"},
  {"fr": "WOOD", "en": "WOOD"},
  {"fr": "ANGELINA", "en": "ANGELINA"},
  {"fr": "ALICIA", "en": "ALICIA"},
  {"fr": "KATIE", "en": "KATIE"},
  {"fr": "JORDAN", "en": "JORDAN"},
  {"fr": "VERNON", "en": "VERNON"},
  {"fr": "PETUNIA", "en": "PETUNIA"},
  {"fr": "DUDLEY", "en": "DUDLEY"},
  {"fr": "MARGE", "en": "MARGE"},
  {"fr": "LILY", "en": "LILY"},
  {"fr": "JAMES", "en": "JAMES"},
  {"fr": "REGULUS", "en": "REGULUS"},
  {"fr": "KREACHER", "en": "KREACHER"},
  {"fr": "DOBBY", "en": "DOBBY"},
  {"fr": "WINKY", "en": "WINKY"},
  {"fr": "HOCKEY", "en": "HOKEY"},
  {"fr": "GRIPHOOK", "en": "GRIPHOOK"},
  {"fr": "BANDEUR", "en": "BOGROD"},
  {"fr": "BANE", "en": "BANE"},
  {"fr": "MAGORIAN", "en": "MAGORIAN"},
  {"fr": "FIRENZE", "en": "FIRENZE"},
  {"fr": "RONAN", "en": "RONAN"},
  {"fr": "ARAGOG", "en": "ARAGOG"},
  {"fr": "MOSAG", "en": "MOSAG"},
  {"fr": "FUMSEC", "en": "FAWKES"},
  {"fr": "BUCK", "en": "BUCKBEAK"},
  {"fr": "CROCDUR", "en": "FANG"},
  {"fr": "PATTE EN ROND", "en": "CROOKSHANKS"},
  {"fr": "MISS TEIGNE", "en": "MRS NORRIS"},
  {"fr": "TREVOR", "en": "TREVOR"},
  {"fr": "EDWIGE", "en": "HEDWIG"},
  {"fr": "COQ", "en": "PIGWIDGEON"},
  {"fr": "ERROL", "en": "ERROL"},
  {"fr": "NAGINI", "en": "NAGINI"},
  {"fr": "FLUFFY", "en": "FLUFFY"},
  {"fr": "NORBERT", "en": "NORBERT"},
  {"fr": "SOMBRAL", "en": "THESTRAL"},
  {"fr": "PEEVES", "en": "PEEVES"},
  {"fr": "MIMI", "en": "MYRTLE"},
  {"fr": "NICK", "en": "NICK"},
  {"fr": "BARON", "en": "BARON"},
  {"fr": "MOINE", "en": "FRIAR"},
  {"fr": "DAME GRISE", "en": "GREY LADY"},
  {"fr": "BINNS", "en": "BINNS"},
  {"fr": "POMFREY", "en": "POMFREY"},
  {"fr": "PINCE", "en": "PINCE"},
  {"fr": "GRYFFONDOR", "en": "GRYFFINDOR"},
  {"fr": "SERPENTARD", "en": "SLYTHERIN"},
  {"fr": "SERDAIGLE", "en": "RAVENCLAW"},
  {"fr": "POUFSOUFFLE", "en": "HUFFLEPUFF"},
  {"fr": "MERLIN", "en": "MERLIN"},
  {"fr": "FLAMEL", "en": "FLAMEL"},
  {"fr": "OLLIVANDER", "en": "OLLIVANDER"},
  {"fr": "MADAME GUIPURE", "en": "MALKIN"},
  {"fr": "BARJOW", "en": "BORGIN"},
  {"fr": "BURKE", "en": "BURKE"},
  {"fr": "ROSMERTA", "en": "ROSMERTA"},
  {"fr": "ABERFORTH", "en": "ABERFORTH"},
  {"fr": "ARIANNA", "en": "ARIANA"},
  {"fr": "KENDRA", "en": "KENDRA"},
  {"fr": "PERCIVAL", "en": "PERCIVAL"},
  {"fr": "GAUNT", "en": "GAUNT"},
  {"fr": "MORFIN", "en": "MORFIN"},
  {"fr": "MARVOLO", "en": "MARVOLO"},
  {"fr": "MEROPE", "en": "MEROPE"},
  {"fr": "RIDDLE", "en": "RIDDLE"},
  {"fr": "HEPZIBAH", "en": "HEPZIBAH"},
  {"fr": "GREYBACK", "en": "GREYBACK"},
  {"fr": "AMYCUS", "en": "AMYCUS"},
  {"fr": "ALECTO", "en": "ALECTO"},
  {"fr": "CARROW", "en": "CARROW"},
  {"fr": "YAXLEY", "en": "YAXLEY"},
  {"fr": "ROOKWOOD", "en": "ROOKWOOD"},
  {"fr": "DOLOHOV", "en": "DOLOHOV"},
  {"fr": "MACNAIR", "en": "MACNAIR"},
  {"fr": "AVERY", "en": "AVERY"},
  {"fr": "MULCIBER", "en": "MULCIBER"},
  {"fr": "ROSIER", "en": "ROSIER"},
  {"fr": "TRAVERS", "en": "TRAVERS"},
  {"fr": "SCABIOR", "en": "SCABIOR"},
  {"fr": "SKEETER", "en": "SKEETER"},
  {"fr": "RITA", "en": "RITA"},
  {"fr": "FIGG", "en": "FIGG"},
  {"fr": "FLETCHER", "en": "FLETCHER"},
  {"fr": "MONDINGUS", "en": "MUNDUNGUS"},
  {"fr": "DODGE", "en": "DOGE"},
  {"fr": "MARCHBANKS", "en": "MARCHBANKS"}
];

// Helper to extract words by language
export function getHarryPotterWords(language: Language): string[] {
  const concepts = HP_CONCEPTS.map((c) => c[language]);
  const characters = HP_CHARACTERS.map((c) => c[language]);
  return [...concepts, ...characters];
}

// Fisher-Yates with deterministic PRNG
function shuffleWithPrng<T>(array: T[], random: () => number): T[] {
  const copy = [...array];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy;
}

// Build balanced 25-card board with ~7 characters and ~18 concepts
export function buildHarryPotterBoardWords(
  language: Language,
  random: () => number,
  characterRatio = 0.28
): string[] {
  const charCount = Math.round(25 * characterRatio); // ~7
  const conceptCount = 25 - charCount; // ~18

  const conceptPool = HP_CONCEPTS.map((c) => c[language]);
  const characterPool = HP_CHARACTERS.map((c) => c[language]);

  const shuffledConcepts = shuffleWithPrng(conceptPool, random);
  const shuffledCharacters = shuffleWithPrng(characterPool, random);

  const pickedConcepts = shuffledConcepts.slice(0, conceptCount);
  const pickedCharacters = shuffledCharacters.slice(0, charCount);

  // Merge and shuffle positions
  return shuffleWithPrng([...pickedConcepts, ...pickedCharacters], random);
}
